{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "vvc.fullname" . }}
  labels: {{- include "vvc.labels.standard" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get"]
{{- end }}
