apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "vvc.fullname" . }}
  labels: {{- include "vvc.labels.standard" . | nindent 4 }}
data:
  config.yml: |
    clusterServerCfg:
      masterURL:
      kubeConfig:
    veleroVolumeCfg:
      includeNamespaces: {{ .Values.config.includeNamespaces }}
      excludeNamespaces: {{ .Values.config.excludeNamespaces }}
      includeVolumeTypes: {{ .Values.config.includeVolumeTypes }}
      excludeVolumeTypes: {{ .Values.config.excludeVolumeTypes }}
      includeStorageClasses: {{ .Values.config.includeStorageClasses }}
      excludeStorageClasses: {{ .Values.config.excludeStorageClasses }}
      excludeJobs: "{{ .Values.config.excludeJobs }}"
