apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vvc.fullname" . }}
  labels: {{- include "vvc.labels.standard" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels: {{- include "vvc.labels.standard" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "vvc.labels.standard" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - name: velero-volume-controller
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /velero-volume-controller/examples
              readOnly: true
      serviceAccountName: {{ include "vvc.serviceAccountName" . }}
      {{- if .Values.podSecurityContext }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: velero-volume-controller
