
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vvc.serviceAccountName" . }}
  labels: {{- include "vvc.labels.standard" . | nindent 4 }}
{{- end }}
